version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartsplit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../backend
      dockerfile: auth-service/Dockerfile
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/smartsplit?sslmode=disable
      JWT_SECRET: devsecret
      PORT: "4000"
      KAFKA_BROKERS: kafka:9092
      REDIS_ADDR: redis:6379
    ports:
      - "4000:4000"

volumes:
  pgdata:
